/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout.index'
import { Route as LayoutSearchRouteImport } from './routes/_layout.search'
import { Route as LayoutVenuesSlugRouteImport } from './routes/_layout.venues.$slug'
import { Route as LayoutVenuesSlugBookRouteImport } from './routes/_layout.venues.$slug_.book'
import { Route as LayoutVenuesSlugConfirmRouteImport } from './routes/_layout.venues.$slug_.confirm'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSearchRoute = LayoutSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutVenuesSlugRoute = LayoutVenuesSlugRouteImport.update({
  id: '/venues/$slug',
  path: '/venues/$slug',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutVenuesSlugBookRoute = LayoutVenuesSlugBookRouteImport.update({
  id: '/venues/$slug_/book',
  path: '/venues/$slug/book',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutVenuesSlugConfirmRoute = LayoutVenuesSlugConfirmRouteImport.update({
  id: '/venues/$slug_/confirm',
  path: '/venues/$slug/confirm',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/search': typeof LayoutSearchRoute
  '/venues/$slug': typeof LayoutVenuesSlugRoute
  '/venues/$slug/book': typeof LayoutVenuesSlugBookRoute
  '/venues/$slug/confirm': typeof LayoutVenuesSlugConfirmRoute
}
export interface FileRoutesByTo {
  '/search': typeof LayoutSearchRoute
  '/': typeof LayoutIndexRoute
  '/venues/$slug': typeof LayoutVenuesSlugRoute
  '/venues/$slug/book': typeof LayoutVenuesSlugBookRoute
  '/venues/$slug/confirm': typeof LayoutVenuesSlugConfirmRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/search': typeof LayoutSearchRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/venues/$slug': typeof LayoutVenuesSlugRoute
  '/_layout/venues/$slug_/book': typeof LayoutVenuesSlugBookRoute
  '/_layout/venues/$slug_/confirm': typeof LayoutVenuesSlugConfirmRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/search' | '/venues/$slug' | '/venues/$slug/book' | '/venues/$slug/confirm'
  fileRoutesByTo: FileRoutesByTo
  to: '/search' | '/' | '/venues/$slug' | '/venues/$slug/book' | '/venues/$slug/confirm'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/search'
    | '/_layout/'
    | '/_layout/venues/$slug'
    | '/_layout/venues/$slug_/book'
    | '/_layout/venues/$slug_/confirm'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/search': {
      id: '/_layout/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof LayoutSearchRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/venues/$slug': {
      id: '/_layout/venues/$slug'
      path: '/venues/$slug'
      fullPath: '/venues/$slug'
      preLoaderRoute: typeof LayoutVenuesSlugRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/venues/$slug_/book': {
      id: '/_layout/venues/$slug_/book'
      path: '/venues/$slug/book'
      fullPath: '/venues/$slug/book'
      preLoaderRoute: typeof LayoutVenuesSlugBookRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/venues/$slug_/confirm': {
      id: '/_layout/venues/$slug_/confirm'
      path: '/venues/$slug/confirm'
      fullPath: '/venues/$slug/confirm'
      preLoaderRoute: typeof LayoutVenuesSlugConfirmRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutSearchRoute: typeof LayoutSearchRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutVenuesSlugRoute: typeof LayoutVenuesSlugRoute
  LayoutVenuesSlugBookRoute: typeof LayoutVenuesSlugBookRoute
  LayoutVenuesSlugConfirmRoute: typeof LayoutVenuesSlugConfirmRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutSearchRoute: LayoutSearchRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutVenuesSlugRoute: LayoutVenuesSlugRoute,
  LayoutVenuesSlugBookRoute: LayoutVenuesSlugBookRoute,
  LayoutVenuesSlugConfirmRoute: LayoutVenuesSlugConfirmRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
